<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dushime Mudahera Richard 76250043">

<title>Homework 3 - DSP1 - 2025/2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/clipboard/clipboard.min.js"></script>
<script src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/quarto-html/quarto.js"></script>
<script src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/quarto-html/popper.min.js"></script>
<script src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/quarto-html/anchor.min.js"></script>
<link href="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#ordinal-regression-and-beta-regression" id="toc-ordinal-regression-and-beta-regression" class="nav-link active" data-scroll-target="#ordinal-regression-and-beta-regression">Ordinal regression and beta regression</a></li>
  <li><a href="#ordinal-regression" id="toc-ordinal-regression" class="nav-link" data-scroll-target="#ordinal-regression">Ordinal regression</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">setup</a>
  <ul class="collapse">
  <li><a href="#loading-and-preparing-data" id="toc-loading-and-preparing-data" class="nav-link" data-scroll-target="#loading-and-preparing-data">Loading and Preparing Data</a></li>
  </ul></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model">Fitting the Model</a>
  <ul class="collapse">
  <li><a href="#differences-in-ratings-between-panel-types" id="toc-differences-in-ratings-between-panel-types" class="nav-link" data-scroll-target="#differences-in-ratings-between-panel-types">Differences in Ratings Between Panel Types</a></li>
  <li><a href="#effect-of-age" id="toc-effect-of-age" class="nav-link" data-scroll-target="#effect-of-age">Effect of Age</a></li>
  <li><a href="#effect-of-nature-relatedness-nr.mu" id="toc-effect-of-nature-relatedness-nr.mu" class="nav-link" data-scroll-target="#effect-of-nature-relatedness-nr.mu">Effect of Nature Relatedness (NR.mu)</a></li>
  <li><a href="#visualization-of-boundaries" id="toc-visualization-of-boundaries" class="nav-link" data-scroll-target="#visualization-of-boundaries">Visualization of Boundaries</a></li>
  <li><a href="#probit-model-and-comparison" id="toc-probit-model-and-comparison" class="nav-link" data-scroll-target="#probit-model-and-comparison">Probit Model and Comparison</a></li>
  </ul></li>
  <li><a href="#beta-regression" id="toc-beta-regression" class="nav-link" data-scroll-target="#beta-regression">Beta regression</a>
  <ul class="collapse">
  <li><a href="#setup-1" id="toc-setup-1" class="nav-link" data-scroll-target="#setup-1">setup</a></li>
  <li><a href="#loading-data" id="toc-loading-data" class="nav-link" data-scroll-target="#loading-data">loading data</a></li>
  <li><a href="#proportion-of-women-in-parliament-by-quota" id="toc-proportion-of-women-in-parliament-by-quota" class="nav-link" data-scroll-target="#proportion-of-women-in-parliament-by-quota">Proportion of Women in Parliament by Quota</a></li>
  <li><a href="#fit-beta-regression-model" id="toc-fit-beta-regression-model" class="nav-link" data-scroll-target="#fit-beta-regression-model">Fit Beta Regression Model</a></li>
  <li><a href="#proportion-by-quota" id="toc-proportion-by-quota" class="nav-link" data-scroll-target="#proportion-by-quota">Proportion by Quota</a></li>
  <li><a href="#proportion-by-polyarchy" id="toc-proportion-by-polyarchy" class="nav-link" data-scroll-target="#proportion-by-polyarchy">Proportion by Polyarchy</a></li>
  <li><a href="#explanation-of-outcomes" id="toc-explanation-of-outcomes" class="nav-link" data-scroll-target="#explanation-of-outcomes">Explanation of Outcomes</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 3 - DSP1 - 2025/2026</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dushime Mudahera Richard 76250043 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>Homework 3</p>
<p>Step 1: Rename this file as follows: “DSP1-HW3-Name-StudentID” with your name and student ID replacing the appropriate parts. Step 2: Update the author field in the YAML as indicated. Step 3: Ensure the document has a Table of Contents when rendered (hint: you set this in the YAML) Step 3: Complete to the Tasks below. Be sure to add meaningful label tags to each R code chunk and structure your analysis sensibly. Step 4: Render to html or pdf (you may need to change target formats in the YAML) Step 5: Zip (or otherwise compress) the html other relevant support folders and include this qmd file with your work filled in Step 6: Submit the compressed folder which should be named “DSP1-HW3-Name-StudentID” through the e-classroom by Tuesday 6 January 2026.</p>
<p>Hint: Make sure that when I open the html file I can view all the embedded images, see all your code and easily identify your responses to questions.</p>
<p>Note: Please see the rules for using AI on the e-classroom.</p>
<section id="ordinal-regression-and-beta-regression" class="level2">
<h2 class="anchored" data-anchor-id="ordinal-regression-and-beta-regression">Ordinal regression and beta regression</h2>
<p>This homework will cover two regression types: logistic and ordinal regression.</p>
</section>
<section id="ordinal-regression" class="level2">
<h2 class="anchored" data-anchor-id="ordinal-regression">Ordinal regression</h2>
<p>A recent survey asked respondents to rate wood wall panels they viewed on a several semantic differential scales. These scales use two adjectives with opposite meanings and ask respondents to describe some stimuli by selecting a point on the scale between the two adjectives.</p>
<p>In this case, the scale was between artificial and natural with the following ordered categories:</p>
<p>Artificial, Somewhat artificial, Neutral, Somewhat Natural, Natural</p>
<p>The data set “artificial_natural.csv” includes a numeric version of this scale (-2 to 2) and a character version.</p>
<p>Fit a an ordinal regression model that uses the character version of the scale (“labs” in the data provided) as the dependent variable and Panel (8 level categorical), Age (numeric, continuous), and NR.mu (numeric, continuous) as the predictor variables. Use a <em>logit</em> link function. “labs” will need to be converted to an ordered factor with the factors in the correct order as above. The other variables are self explanatory enough, but NR.mu is the mean score of the items on the nature relatedness scale <a href="https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2013.00813/full">NR-6 version</a>.</p>
<ol type="1">
<li>Are there differences in ratings between panel types? Provide a text explanation and visualisation that illustrates the differences on the probability scale.</li>
<li>What is the effect of age? Is it meaningful? Provide a text explanation and a visualisation to explain the outcome.</li>
<li>Does nature relatedness have an effect? Provide a text explanation and a visualisation to explain the outcome.</li>
<li>Create a visualisation of the boundaries between artificial-natural scale categories overlaid on a logistic distribution for the 2waycladding panel (baseline unless you change something) and the singlebrown panel (two separate visualisations are ok) In each, highlight the probability of selecting “somewhat natural” by using a fill between the boundaries for that category and label of the probability of selecting that category.</li>
<li>Refit the model using a <em>probit</em> link. State which model you prefer between the logit and probit model and why. (Refer to the Bürkner and Vuorre (2019) reading on the e-classroom for support.)</li>
</ol>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">setup</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.5.1
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ordinal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ordinal'

The following object is masked from 'package:dplyr':

    slice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: viridisLite</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>palette <span class="ot">&lt;-</span> <span class="fu">viridis</span>(<span class="dv">10</span>, <span class="at">option =</span> <span class="st">"magma"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">%notin%</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">Negate</span>(<span class="st">`</span><span class="at">%in%</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="loading-and-preparing-data" class="level3">
<h3 class="anchored" data-anchor-id="loading-and-preparing-data">Loading and Preparing Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>d.an <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/artificial_natural.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2387 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Panel, labs
dbl (3): Value, Age, NR.mu

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>an_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Artificial"</span>, <span class="st">"Somewhat artificial"</span>, <span class="st">"Neutral"</span>, <span class="st">"Somewhat natural"</span>, <span class="st">"Natural"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>d.an <span class="ot">&lt;-</span> d.an <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">labs =</span> <span class="fu">factor</span>(labs, <span class="at">levels =</span> an_levels, <span class="at">ordered =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d.an)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Value            Panel                Age            NR.mu      
 Min.   :-2.0000   Length:2387        Min.   : 1.00   Min.   :1.000  
 1st Qu.: 0.0000   Class :character   1st Qu.:31.00   1st Qu.:3.400  
 Median : 1.0000   Mode  :character   Median :44.00   Median :4.000  
 Mean   : 0.7956                      Mean   :44.03   Mean   :3.801  
 3rd Qu.: 2.0000                      3rd Qu.:56.00   3rd Qu.:4.250  
 Max.   : 2.0000                      Max.   :99.00   Max.   :5.000  
                  labs    
 Artificial         :103  
 Somewhat artificial:283  
 Neutral            :491  
 Somewhat natural   :632  
 Natural            :878  
                          </code></pre>
</div>
</div>
</section>
</section>
<section id="fitting-the-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model">Fitting the Model</h2>
<p>Uses the <code>clm</code> function from the <code>ordinal</code> package with a logit link.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>model.logit <span class="ot">&lt;-</span> <span class="fu">clm</span>(labs <span class="sc">~</span> Panel <span class="sc">+</span> Age <span class="sc">+</span> NR.mu, <span class="at">data =</span> d.an, <span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: labs ~ Panel + Age + NR.mu
data:    d.an

 link  threshold nobs logLik   AIC     niter max.grad cond.H 
 logit flexible  2387 -3111.11 6248.22 5(0)  5.05e-09 3.9e+05

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
Panelbrownverticals  0.082560   0.146993   0.562   0.5743    
Panelcleavedpattern  0.145191   0.148200   0.980   0.3272    
Panelclt             1.081905   0.154486   7.003 2.50e-12 ***
Panellogwall         2.154615   0.172953  12.458  &lt; 2e-16 ***
Paneloakverticals   -0.327574   0.146418  -2.237   0.0253 *  
Panelosb            -1.390535   0.152154  -9.139  &lt; 2e-16 ***
Panelsinglebrown     0.677457   0.148731   4.555 5.24e-06 ***
Age                  0.016346   0.002508   6.517 7.19e-11 ***
NR.mu                0.307083   0.052670   5.830 5.53e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
                               Estimate Std. Error z value
Artificial|Somewhat artificial  -1.3324     0.2597  -5.130
Somewhat artificial|Neutral      0.2414     0.2470   0.977
Neutral|Somewhat natural         1.5275     0.2473   6.177
Somewhat natural|Natural         2.8473     0.2524  11.282</code></pre>
</div>
</div>
<section id="differences-in-ratings-between-panel-types" class="level3">
<h3 class="anchored" data-anchor-id="differences-in-ratings-between-panel-types">Differences in Ratings Between Panel Types</h3>
<p>To assess differences, we examine the coefficients for each Panel level relative to the baseline (2waycladding). Significant p-values indicate differences. Positive coefficients suggest a shift towards more “Natural” ratings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>newdata_panel <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">Panel =</span> <span class="fu">unique</span>(d.an<span class="sc">$</span>Panel), </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Age =</span> <span class="fu">mean</span>(d.an<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">NR.mu =</span> <span class="fu">mean</span>(d.an<span class="sc">$</span>NR.mu, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>preds_panel <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.logit, <span class="at">newdata =</span> newdata_panel, <span class="at">type =</span> <span class="st">"prob"</span>)<span class="sc">$</span>fit</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>newdata_panel <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdata_panel, preds_panel) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">all_of</span>(an_levels), <span class="at">names_to =</span> <span class="st">"Category"</span>, <span class="at">values_to =</span> <span class="st">"Probability"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Category =</span> <span class="fu">factor</span>(Category, <span class="at">levels =</span> an_levels))</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newdata_panel, <span class="fu">aes</span>(<span class="at">x =</span> Panel, <span class="at">y =</span> Probability, <span class="at">fill =</span> Category)) <span class="sc">+</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"magma"</span>) <span class="sc">+</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Predicted Probabilities by Panel Type"</span>, <span class="at">y =</span> <span class="st">"Probability"</span>, <span class="at">x =</span> <span class="st">"Panel"</span>) <span class="sc">+</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/panel-probs-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Panels such as “logwall” and “clt” have significant positive coefficients, indicating they are perceived as more natural compared to the baseline “2waycladding”.</p>
<p>For “singlebrown” also shows a positive effect . Conversely, “osb” and “oakverticals” have significant negative coefficients, suggesting more artificial perceptions.</p>
<p>For “brownverticals” and “cleavedpattern” are not significantly different from the baseline.</p>
<p>The visualization shows probability distributions across categories for each panel, holding Age and NR.mu at their means.</p>
</section>
<section id="effect-of-age" class="level3">
<h3 class="anchored" data-anchor-id="effect-of-age">Effect of Age</h3>
<p>The coefficient for Age is 0.0163 with p-value 7.19e-11, indicating a significant positive effect. Older participants tend to rate panels as more natural.</p>
<p>Is it meaningful? The effect size is small (0.016 per year), but statistically significant, suggesting a gradual shift towards more natural perceptions with increasing age.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>newdata_age <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">Age =</span> <span class="fu">seq</span>(<span class="fu">min</span>(d.an<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">max</span>(d.an<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">length.out =</span> <span class="dv">50</span>),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">Panel =</span> <span class="st">"2waycladding"</span>,  <span class="co"># Baseline</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">NR.mu =</span> <span class="fu">mean</span>(d.an<span class="sc">$</span>NR.mu, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>preds_age <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.logit, <span class="at">newdata =</span> newdata_age, <span class="at">type =</span> <span class="st">"prob"</span>)<span class="sc">$</span>fit</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>newdata_age <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdata_age, preds_age) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">all_of</span>(an_levels), <span class="at">names_to =</span> <span class="st">"Category"</span>, <span class="at">values_to =</span> <span class="st">"Probability"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Category =</span> <span class="fu">factor</span>(Category, <span class="at">levels =</span> an_levels))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting </span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newdata_age, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Probability, <span class="at">color =</span> Category, <span class="at">group =</span> Category)) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">option =</span> <span class="st">"magma"</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Predicted Probabilities Across Age"</span>, <span class="at">y =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/age-effect-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="effect-of-nature-relatedness-nr.mu" class="level3">
<h3 class="anchored" data-anchor-id="effect-of-nature-relatedness-nr.mu">Effect of Nature Relatedness (NR.mu)</h3>
<p>The coefficient for NR.mu is 0.307 with p-value 5.53e-09, showing a significant positive effect. Higher nature relatedness leads to more “Natural” ratings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>newdata_nr <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">NR.mu =</span> <span class="fu">seq</span>(<span class="fu">min</span>(d.an<span class="sc">$</span>NR.mu, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">max</span>(d.an<span class="sc">$</span>NR.mu, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">length.out =</span> <span class="dv">50</span>),</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Panel =</span> <span class="st">"2waycladding"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Age =</span> <span class="fu">mean</span>(d.an<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>preds_nr <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.logit, <span class="at">newdata =</span> newdata_nr, <span class="at">type =</span> <span class="st">"prob"</span>)<span class="sc">$</span>fit</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>newdata_nr <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdata_nr, preds_nr) <span class="sc">%&gt;%</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">all_of</span>(an_levels), <span class="at">names_to =</span> <span class="st">"Category"</span>, <span class="at">values_to =</span> <span class="st">"Probability"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Category =</span> <span class="fu">factor</span>(Category, <span class="at">levels =</span> an_levels))</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newdata_nr, <span class="fu">aes</span>(<span class="at">x =</span> NR.mu, <span class="at">y =</span> Probability, <span class="at">color =</span> Category, <span class="at">group =</span> Category)) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">option =</span> <span class="st">"magma"</span>) <span class="sc">+</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Predicted Probabilities Across NR.mu"</span>, <span class="at">y =</span> <span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/nr-effect-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="visualization-of-boundaries" class="level3">
<h3 class="anchored" data-anchor-id="visualization-of-boundaries">Visualization of Boundaries</h3>
<p>For the logit link, we plot the logistic density with thresholds. Highlight “Somewhat natural” (between tau[3] and tau[4]).</p>
<p>For 2waycladding (baseline, no shift).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>tau <span class="ot">&lt;-</span> model.logit<span class="sc">$</span>alpha</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>latent_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>, <span class="at">length.out =</span> <span class="dv">500</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">dlogis</span>(x))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>prob_sn <span class="ot">&lt;-</span> <span class="fu">plogis</span>(tau[<span class="dv">4</span>]) <span class="sc">-</span> <span class="fu">plogis</span>(tau[<span class="dv">3</span>])</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(latent_df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> tau, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> <span class="fu">filter</span>(latent_df, x <span class="sc">&gt;</span> tau[<span class="dv">3</span>] <span class="sc">&amp;</span> x <span class="sc">&lt;</span> tau[<span class="dv">4</span>]), <span class="fu">aes</span>(<span class="at">y =</span> y), <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> (tau[<span class="dv">3</span>] <span class="sc">+</span> tau[<span class="dv">4</span>])<span class="sc">/</span><span class="dv">2</span>, <span class="at">y =</span> <span class="fl">0.05</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"Somewhat natural</span><span class="sc">\n</span><span class="st">Prob:"</span>, <span class="fu">round</span>(prob_sn, <span class="dv">3</span>))) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Latent Scale for 2waycladding"</span>, <span class="at">x =</span> <span class="st">"Latent Variable"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/boundaries-baseline-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For singlebrown: Shift by its coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>coef_sb <span class="ot">&lt;-</span> <span class="fu">coef</span>(model.logit)[<span class="st">"Panelsinglebrown"</span>]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>latent_df_sb <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>, <span class="at">length.out =</span> <span class="dv">500</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">dlogis</span>(x), <span class="at">x_shifted =</span> x <span class="sc">-</span> coef_sb)  <span class="co"># Shift left if positive coef (towards more natural)</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>prob_sn_sb <span class="ot">&lt;-</span> <span class="fu">plogis</span>(tau[<span class="dv">4</span>] <span class="sc">-</span> coef_sb) <span class="sc">-</span> <span class="fu">plogis</span>(tau[<span class="dv">3</span>] <span class="sc">-</span> coef_sb)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(latent_df_sb, <span class="fu">aes</span>(<span class="at">x =</span> x_shifted, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> tau <span class="sc">-</span> coef_sb, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> <span class="fu">filter</span>(latent_df_sb, x_shifted <span class="sc">&gt;</span> tau[<span class="dv">3</span>] <span class="sc">-</span> coef_sb <span class="sc">&amp;</span> x_shifted <span class="sc">&lt;</span> tau[<span class="dv">4</span>] <span class="sc">-</span> coef_sb), <span class="fu">aes</span>(<span class="at">y =</span> y), <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> (tau[<span class="dv">3</span>] <span class="sc">+</span> tau[<span class="dv">4</span>])<span class="sc">/</span><span class="dv">2</span> <span class="sc">-</span> coef_sb, <span class="at">y =</span> <span class="fl">0.05</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"Somewhat natural</span><span class="sc">\n</span><span class="st">Prob:"</span>, <span class="fu">round</span>(prob_sn_sb, <span class="dv">3</span>))) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Latent Scale for singlebrown"</span>, <span class="at">x =</span> <span class="st">"Latent Variable"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/boundaries-singlebrown-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="probit-model-and-comparison" class="level3">
<h3 class="anchored" data-anchor-id="probit-model-and-comparison">Probit Model and Comparison</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model.probit <span class="ot">&lt;-</span> <span class="fu">clm</span>(labs <span class="sc">~</span> Panel <span class="sc">+</span> Age <span class="sc">+</span> NR.mu, <span class="at">data =</span> d.an, <span class="at">link =</span> <span class="st">"probit"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.probit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: labs ~ Panel + Age + NR.mu
data:    d.an

 link   threshold nobs logLik   AIC     niter max.grad cond.H 
 probit flexible  2387 -3114.00 6253.99 5(0)  4.37e-12 3.8e+05

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
Panelbrownverticals  0.046328   0.086740   0.534   0.5933    
Panelcleavedpattern  0.071929   0.087124   0.826   0.4090    
Panelclt             0.620492   0.090333   6.869 6.47e-12 ***
Panellogwall         1.285049   0.098750  13.013  &lt; 2e-16 ***
Paneloakverticals   -0.183090   0.086389  -2.119   0.0341 *  
Panelosb            -0.789619   0.088302  -8.942  &lt; 2e-16 ***
Panelsinglebrown     0.411156   0.088352   4.654 3.26e-06 ***
Age                  0.009747   0.001451   6.719 1.83e-11 ***
NR.mu                0.176257   0.030853   5.713 1.11e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
                               Estimate Std. Error z value
Artificial|Somewhat artificial  -0.6878     0.1465  -4.696
Somewhat artificial|Neutral      0.1338     0.1432   0.934
Neutral|Somewhat natural         0.8835     0.1434   6.162
Somewhat natural|Natural         1.6771     0.1453  11.545</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model.logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6248.222</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(model.probit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6253.992</code></pre>
</div>
</div>
<p>I prefer the Logit model. Not only is the AIC lower (6248.22 vs 6253.99), indicating a better statistical fit, but the logit link is also more interpretable in psychology. Following Bürkner and Vuorre (2019), the logit model allows us to interpret the coefficients as Odds Ratios. For example, the nature relatedness (NR.mu) estimate of 0.307 implies that for every 1-unit increase in nature relatedness, the odds of a respondent moving to a ‘more natural’ category increase by approximately 36% (<span class="math inline">\(e^{0.307} \approx 1.36\)</span></p>
</section>
</section>
<section id="beta-regression" class="level2">
<h2 class="anchored" data-anchor-id="beta-regression">Beta regression</h2>
<p>Use the attached data about democracy worldwide. It is a subset from the (Varieties of Democracy)[https://www.v-dem.net] project (V-Dem). You will model the proportion of female (prop_fem) members of parliament (MP) with different predictors.</p>
<p>The data is in the “vdem_2020_subset.csv” file.</p>
<ol type="1">
<li>Visualise the proportion of women in parliament based on quota in two different ways.</li>
<li>Fit a beta regression with prop_fem as the response variable with quota and polyarchy (degree of democracy) as predictor variables.</li>
<li>Visualise the proportion of women MPs based on quota</li>
<li>Visualise the proportion of women MPs based on polyarchy</li>
<li>Write a brief explanation of the outcomes, refer to previous visualisations or create new ones to help with the explanation.</li>
</ol>
<section id="setup-1" class="level3">
<h3 class="anchored" data-anchor-id="setup-1">setup</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(betareg)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>palette <span class="ot">&lt;-</span> <span class="fu">viridis</span>(<span class="dv">10</span>, <span class="at">option =</span> <span class="st">"turbo"</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>inv.logit <span class="ot">&lt;-</span> <span class="cf">function</span>(x) { <span class="fu">exp</span>(x) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(x)) }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-data" class="level3">
<h3 class="anchored" data-anchor-id="loading-data">loading data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>d.vdem <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/vdem_2020_subset.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 170 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): country_name, country_text_id
dbl (6): year, region, polyarchy, corruption, civil_liberties, prop_fem
lgl (1): quota

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(d.vdem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> country_name       country_text_id         year          region     
 Length:170         Length:170         Min.   :2020   Min.   :1.000  
 Class :character   Class :character   1st Qu.:2020   1st Qu.:2.000  
 Mode  :character   Mode  :character   Median :2020   Median :4.000  
                                       Mean   :2020   Mean   :3.518  
                                       3rd Qu.:2020   3rd Qu.:5.000  
                                       Max.   :2020   Max.   :6.000  
   polyarchy       corruption     civil_liberties     prop_fem     
 Min.   : 1.50   Min.   :0.0020   Min.   :0.0240   Min.   :0.0033  
 1st Qu.:28.95   1st Qu.:0.1910   1st Qu.:0.4985   1st Qu.:0.1669  
 Median :53.05   Median :0.5215   Median :0.7645   Median :0.2402  
 Mean   :51.76   Mean   :0.4861   Mean   :0.6786   Mean   :0.2502  
 3rd Qu.:75.85   3rd Qu.:0.7665   3rd Qu.:0.8860   3rd Qu.:0.3180  
 Max.   :91.70   Max.   :0.9620   Max.   :0.9630   Max.   :0.6125  
   quota        
 Mode :logical  
 FALSE:85       
 TRUE :85       
                
                
                </code></pre>
</div>
</div>
</section>
<section id="proportion-of-women-in-parliament-by-quota" class="level3">
<h3 class="anchored" data-anchor-id="proportion-of-women-in-parliament-by-quota">Proportion of Women in Parliament by Quota</h3>
<p>Way 1: Boxplot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d.vdem, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(quota, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)), <span class="at">y =</span> prop_fem)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot: Prop Fem by Quota"</span>, <span class="at">x =</span> <span class="st">"Quota"</span>, <span class="at">y =</span> <span class="st">"Proportion Female MPs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/boxplot-quota-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Way 2: Density Plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d.vdem, <span class="fu">aes</span>(<span class="at">x =</span> prop_fem, <span class="at">fill =</span> <span class="fu">factor</span>(quota, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)))) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density: Prop Fem by Quota"</span>, <span class="at">x =</span> <span class="st">"Proportion Female MPs"</span>, <span class="at">fill =</span> <span class="st">"Quota"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/density-quota-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fit-beta-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="fit-beta-regression-model">Fit Beta Regression Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model.beta <span class="ot">&lt;-</span> <span class="fu">betareg</span>(prop_fem <span class="sc">~</span> quota <span class="sc">+</span> polyarchy, <span class="at">data =</span> d.vdem)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.beta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
betareg(formula = prop_fem ~ quota + polyarchy, data = d.vdem)

Quantile residuals:
    Min      1Q  Median      3Q     Max 
-3.3270 -0.5050  0.0284  0.6576  2.8119 

Coefficients (mean model with logit link):
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.665081   0.127756 -13.033  &lt; 2e-16 ***
quotaTRUE    0.232163   0.096048   2.417   0.0156 *  
polyarchy    0.008271   0.001908   4.334 1.47e-05 ***

Phi coefficients (precision model with identity link):
      Estimate Std. Error z value Pr(&gt;|z|)    
(phi)    12.01       1.27   9.453   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Type of estimator: ML (maximum likelihood)
Log-likelihood:   130 on 4 Df
Pseudo R-squared: 0.1073
Number of iterations: 14 (BFGS) + 2 (Fisher scoring) </code></pre>
</div>
</div>
</section>
<section id="proportion-by-quota" class="level3">
<h3 class="anchored" data-anchor-id="proportion-by-quota">Proportion by Quota</h3>
<p>Predicted proportions for each quota level, holding polyarchy at mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>preds_quota <span class="ot">&lt;-</span> <span class="fu">predictions</span>(model.beta, <span class="at">by =</span> <span class="st">"quota"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>preds_quota_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(preds_quota)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(preds_quota_df, <span class="fu">aes</span>(<span class="at">x =</span> quota, <span class="at">y =</span> estimate, <span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high)) <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>() <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Predicted Prop Fem by Quota"</span>, <span class="at">y =</span> <span class="st">"Proportion"</span>, <span class="at">x =</span> <span class="st">"Quota"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/preds-quota-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="proportion-by-polyarchy" class="level3">
<h3 class="anchored" data-anchor-id="proportion-by-polyarchy">Proportion by Polyarchy</h3>
<p>Predicted proportions across polyarchy range, holding quota at FALSE (no quota).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>newdata_poly <span class="ot">&lt;-</span> <span class="fu">datagrid</span>(<span class="at">model =</span> model.beta,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">polyarchy =</span> <span class="fu">seq</span>(<span class="fu">min</span>(d.vdem<span class="sc">$</span>polyarchy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">max</span>(d.vdem<span class="sc">$</span>polyarchy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">length.out =</span> <span class="dv">50</span>),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">quota =</span> <span class="cn">FALSE</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>preds_poly <span class="ot">&lt;-</span> <span class="fu">predictions</span>(model.beta, <span class="at">newdata =</span> newdata_poly)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(preds_poly, <span class="fu">aes</span>(<span class="at">x =</span> polyarchy, <span class="at">y =</span> estimate)) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Predicted Prop Fem by Polyarchy (No Quota)"</span>, <span class="at">y =</span> <span class="st">"Proportion"</span>, <span class="at">x =</span> <span class="st">"Polyarchy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DSP1-HW3-Dushime-Mudahera-Richard-76250043_files/figure-html/preds-polyarchy-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="explanation-of-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="explanation-of-outcomes">Explanation of Outcomes</h3>
<p>The beta regression model indicates a significant positive effect of having a quota (estimate = 0.232, SE = 0.096, z = 2.417, p = 0.0156), suggesting that countries with gender quotas have a higher proportion of female MPs. Similarly, polyarchy has a significant positive effect (estimate = 0.008, SE = 0.002, z = 4.334, p &lt; 0.001), implying that higher levels of democracy are associated with greater female representation in parliament.</p>
<p>The pseudo R-squared is 0.1073, indicating that the model explains about 10.7% of the variability in the data. The precision parameter phi is estimated at 12.01, which is significant.</p>
<p>Referring to the visualizations: The boxplot and density plots in Question 1 show that countries with quotas tend to have higher and more concentrated proportions of female MPs around higher values compared to those without. The point-range plot in Question 3 illustrates the model-predicted increase in proportion due to quotas, with non-overlapping confidence intervals suggesting a meaningful difference. The line plot in Question 4 demonstrates a gradual positive relationship between polyarchy and female representation, with the confidence band widening at extreme values due to fewer observations. Overall, these results highlight the roles of institutional (quotas) and systemic (democracy) factors in promoting gender equality in political representation.</p>
<p>Thank you.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>