# -*- coding: utf-8 -*-
"""missionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4iE-gyawklbt4lKKSxXhYfeYzMRgAxz

Define the initial and the goal state.
"""

initial_state = (3, 3, True)
goal_state = (0, 0, False)

"""Print functions"""

def print_state(state):
  (missionary, cannibal, boat) = state
  print(f'({missionary}, {cannibal}, {'T' if boat else 'F'})')

"""Functions for state manipulation."""

def right_state(state):
  (missionary, cannibal, boat) = state
  return (3 - missionary, 3 - cannibal, not boat)

def get_successors(state):
  (missionary, cannibal, boat) = state

  diff = [(1, 0), (2, 0), (0, 1), (0, 2), (1, 1)]

  result = []
  if boat:
    for (dm, dc) in diff:
      new_missionary = missionary - dm
      new_cannibal = cannibal - dc
      if new_missionary < 0 or new_cannibal < 0:
        continue
      new_state = (new_missionary, new_cannibal, not boat)
      result.append(new_state)
  else:
    for (dm, dc) in diff:
      new_missionary = missionary + dm
      new_cannibal = cannibal + dc
      if new_missionary > 3 or new_cannibal > 3:
        continue
      new_state = (new_missionary, new_cannibal, not boat)
      result.append(new_state)

  return result

def got_eaten(state):
  (missionary, cannibal, _) = state
  return cannibal > missionary and missionary > 0

def find_solution(state0, state1, visited=[]):
  if state0 == state1:
    return [state0]

  for successor in get_successors(state0):
    if got_eaten(successor) or got_eaten(right_state(successor)):
      continue

    if successor in visited:
      continue

    solution = find_solution(successor, state1, visited + [state0])
    if solution != []:
      return [state0] + solution

  return []

"""Let's test the functions."""

find_solution(initial_state, goal_state)
